//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string NisNumber { get; set; }
        public string Password { get; set; }
        public int Edad { get; set; }
        public Nullable<int> State { get; set; }
    
        public virtual Cstate Cstate { get; set; }
    }
}
